### ISSUE TITLE
use objc_util. retain_global to keep the Gesture

### ISSUE THREAD

**Issue by jsbain** [mikaelho/pythonista-gestures#1]
Otherwise if you present something in a panel, crashes will occur when running a new script.     The small memory leak is probably more desirable than possibility of crashes.

**Comment by mikaelho** [comment]
Thanks - where is retain_global documented?

**Comment by jsbain** [comment]
it is in the obj_util module.  looks like not in the docs, but i think it is documented in the code itself.  it is used internally in create_objc_class to keep methods from getting cleared when used as callbacks.

**Comment by mikaelho** [comment]
Thanks, looked at the code and saw it is a way to keep any object reference alive in objc_util's internal dict. Implemented and this removed the requirement to keep a reference to the Gestures object.
