### ISSUE TITLE
Add UIGestureRecognizerDelegate

### ISSUE THREAD

**Issue by jsbain** [mikaelho/pythonista-gestures#2]
Not sure if you are still working in this, or if you'd prefer pull requests.  But i have a feature rewuest of sorts

It would be great if a new objc class was created to act as a [UIGestureRecognizerDelegate](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIGestureRecognizerDelegate_Protocol/), and stored in the Gesture object.  Users would then implement their own delegate callbacks, via methods in a `delegate` attribute set in the Gesture.

The main use case would be allowing simultaneous pinch/pan

**Comment by mikaelho** [comment]
Thanks for the idea, sounds like a useful thing. My initial thought is that the delegate (Python object) reference would be given as a parameter of the add_x calls. Maybe you could also set a "global" default on the Gestures class.

**Comment by jsbain** [comment]
I implemented something, see 301bf14.
The most ios-like approach i think would be to have one per Gestures object.  Then you implement the logic within the delegate.

**Comment by mikaelho** [comment]
Implemented now in a way that is intended to be as friendly as possible for the casual Python coder, see 'fine-tuning' section in Readme. Per-Gesture control is achievable by instantiating one Gestures object per gesture.
