### ISSUE TITLE
fail delegates are not called

### ISSUE THREAD

**Issue by mithrendal** [mikaelho/pythonista-gestures#4]
Hi @mikaelho 

in my tests the fail expressions will never be evaluated. It seems this is due to the fact that your code never gets to the following position. Due to this, the call backs (for ..should...fail.. etc.) will never be registrated.
Or did I completely misunderstood something here ?

all the best

https://github.com/mikaelho/pythonista-gestures/blob/0ea1b27b07a15e3bc4057bdaf44072dd4ec0fb07/Gestures.py#L176

**Comment by mikaelho** [comment]
What should happen is that on first execution after Pythonista has been restarted, try fails and the class gets defined. On subsequent runs, the class is already defined and does not need to be redefined.

In all cases the class is used to create a new delegate.

Did that answer your question, or did I completely misunderstand it?

**Comment by mithrendal** [comment]
Hi @mikaelho

Yes that answers my question. The fault was on my side. Your code is completely okay. I did see it in the debugger.  

I am tinkering around with your code as I am unable to disable the default swipe-two-finger-down gesture which closes a view which is presented in fullscreen with hide titlebar. In other words I can not get the fail method to work for disabling Pythonistas built in two finger swipe down gesture.

I altered the following code in the Gestures demo code
...
  bg = ui.View()
  bg.present('fullscreen', hide_title_bar=True)
...

Then I tried to 

  g.fail = lambda gr, other_gr: other_gr == Gestures.SWIPE

But it does not work. The gesture is still executed, which closes the displayed view.

Do you have an idea ? 

I debugged it so far with some print statements. It seems not to get into the following handler

    def gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_(_self, _sel, gr, other_gr):
      print(ObjCInstance(other_gr)._get_objc_classname())

I now think this is because your Gesture handler is registered for the views and subviews only and not for the pythonista key window. So when the key window processes its gestures, it will not ask your fail methode.

When I add this

   thewindow=UIApplication.sharedApplication().keyWindow()
   g.add_swipe(thewindow, pan_or_swipe_handler, direction=Gestures.DOWN)
 
It will print much more gesture recognizers to the console. I spotted a swipe recognizer and i am sure it is pythonistas two finger swipe down gr. 

But nevertheless it still gets executed. 

Maybe I am completely wrong again on this ?

**Comment by mikaelho** [comment]
Are you trying to manage a conflict between two gestures, or disable the two-finger closing gesture completely?

**Comment by mithrendal** [comment]
I like to use your API to completeley disable pythonistas closing gesture only. Like @omz does it in his XCode Template ...  

https://github.com/omz/PythonistaAppTemplate/blob/f560f93f8876d82a21d108977f90583df08d55af/PythonistaAppTemplate/PAAppDelegate.m#L27

Because the closing gesture conflicts with scene touches in my app. 

Is that possible with your GesturesAPI ?

**Comment by mikaelho** [comment]
I tried the omz method with Gestures, do not exactly know why it does not work.

But below is a function you can use to disable the swipe-to-close gesture. Might add it as utility to Gestures.

    #coding: utf-8
    from ui import *
    from objc_util import *
    
    UILayoutContainerView = ObjCClass('UILayoutContainerView')
    UISwipeGestureRecognizer = ObjCClass('UISwipeGestureRecognizer')
    
    def disable_swipe_to_close(view):
      v = view.objc_instance
      while not v.isKindOfClass_(UILayoutContainerView.ptr):
        v = v.superview()
      for gr in v.gestureRecognizers():
        if gr.isKindOfClass_(UISwipeGestureRecognizer.ptr):
          gr.setEnabled(False)
    
    if __name__ == '__main__':
      bg = Button(title='Click me')
      bg.present('fullscreen', hide_title_bar=True)
      disable_swipe_to_close(bg)

**Comment by mithrendal** [comment]
Sweet you solved it !

But not with Gestures().fail or fail_other

Yes, great idea to add this to to Gestures.py maybe like this ?
...
 def getUnderlyingRecognizers( view, listRecognizerTypes ) 
 and
 def enableRecognizers( listOfRecognizers, enable=True )

and one specific method 
def enablePythonistasStdCloseGesture(view, enable=True)
  ...
  list = getUnderlyingRecognizers( view, [ObjCClass('UISwipeGestureRecognizer')] ) 
  disableRecognizers(list, enable)
  ...

**Comment by mikaelho** [comment]
Yes, agree, I was thinking along the same lines. With the addition of Pythonic method names, of course. And maybe also supporting easy replacement of the closing gesture with something else - e.g. maybe you want 4–finger pinch instead.

**Comment by mithrendal** [comment]
//...replacement of the closing gesture with something else...// -->> wow great stuff...

I think we can already close this issue now? Or do you still like to dig around the problem why the fail method doesn't lead the swipe-to-close gesture to fail ?

**Comment by mikaelho** [comment]
Let’s keep it open until I have actually implemented the convenience methods.

**Comment by mikaelho** [comment]
Closed via cbbf0d1bd10dbb7e55a6ad56740d3cdae0178e1e

Just manipulating the close gesture here. More general ”search and enable/disable” type things to be added when there is a real use case.
