### ISSUE TITLE
Key error (Pythonista 3.3 Beta)

### ISSUE THREAD

**Issue by mithrendal** [mikaelho/pythonista-gestures#5]
Hi @mikaelho 
I am in the testflight of pythonista 3.3 Beta.
running my project I have two issues with Gestures

the first one is when I do swipe it does behave correctly but additionally gives me a key error at
https://github.com/mikaelho/pythonista-gestures/blob/cbbf0d1bd10dbb7e55a6ad56740d3cdae0178e1e/Gestures.py#L211

when I click the error popup window of pythonista away then it continues.

(this bug is also visible when running the demo which is contained in Gestures.py)

**Comment by mikaelho** [comment]
Running the included demo on beta 3.3, and swiping right, I do not get this error. Do you have some more info on how to reproduce?

**Comment by mithrendal** [comment]
yes I see this now too. I do not get any error too if cold start pythonista and run the included demo. The strange thing is if I first start my program which uses Gestures.py and afterwards after I close it (no cold start, simply close of my program) and run the demo which is included in Gestures.py then the key error is thrown. The same if I start my program a second time. Is it maybe some references which is not released properly by my program ? I will investigate. I will look at it in the next days or so. The strange thing is, that with an older version of Gestures.py this problem does not occur.

**Comment by mithrendal** [comment]
Hi @mikaelho 
I separated a fully featured WKWebView demo for you at
https://github.com/mithrendal/pythonista_wkwebview

if you start it a second time and swipe to left you can see the key error...

**Comment by ydupas** [comment]
Hi all,
I have the same error with 3.6 and 2.7. 
Ok for the first time, but after key error.
I try to del Gestures object in console, no way.
I try to modify get_self method but the stack trace stop on the same line of code, like I don’t modify it or some compiled script don’t recompiled.

So to solve it, I remove this 3 lines and indent lines after except :
ˋˋˋpython 
try:
      PythonistaGestureDelegate = ObjCClass('PythonistaGestureDelegate')
    except:
ˋˋˋ

**Comment by mikaelho** [comment]
Commit fd309492815d38ce479f27862b3c3cb367d03852 now implements a different method of finding the Python Gestures instance from the ObjC delegate method. Could you please check with this version?

**Comment by mithrendal** [comment]
Hi @mikaelho, 
Just tested this in two projects. It works now. No key error anymore.  Thank you.
In the wkwebkit demo which I made for you it works now too. Was it the kind of code which you were looking for for your current project?  
with best whishes for new year

**Comment by mikaelho** [comment]
Thanks. Closing this and moving WKWebView discussion to that repo. @ydupas, please let us know if your use case still fails.
