### ISSUE TITLE
disable_swipe_to_close (Pythonista 3.3 Beta)

### ISSUE THREAD

**Issue by mithrendal** [mikaelho/pythonista-gestures#6]
Hi @mikaelho 

the call Gestures.disable_swipe_to_close(view) gives an error with the new Beta  

'NoneType' object has no attribute 'isKindOfClass_' 

at

https://github.com/mikaelho/pythonista-gestures/blob/cbbf0d1bd10dbb7e55a6ad56740d3cdae0178e1e/Gestures.py#L407

**Comment by mithrendal** [comment]
Actually this bug was not due to pythonista 3.3 Beta. I also reproduced it now in pythonista 3.2. For version 3.3 I had to decorate my main_setup method with @on_main_thread due to  crashes when I was setting up native objc native views. That resulted in the thrown exception above. What I do is setting up a WKWebkit view and some ui views and at the end of the main method I do call Gestures.disable_swipe_to_close(view). What I discovered is that it is simply not ready for walking down the chain of views to find the one which has the gesture recognizers (to disable them ) and therefore it runs into None object. That happens in both versions 3.2 and 3.3. 
Now when I call the method Gestures.disable_swipe_to_close(view) outside that main view setup method more specifically afterwards or later , then the disable_swipe_to_close method works as intended.

Should I close the issue ? For me it works now...

**Comment by mikaelho** [comment]
Thanks, I was just about to comment that I could not reproduce this issue.

For another project, I would be interested in your WKWebView code. Is it available somewhere?

**Comment by mithrendal** [comment]
Sure I will separate and upload the code for you. It will take some days. Be a bit patient. What I did is a Brigde Pythonista to JS and JS to Pythonista. That means you can call JS Code from pythonista and Python code from JS.

**Comment by mikaelho** [comment]
Excellent, thank you. I believe this would be worth a separate repo, to create an generic Apple-supported alternative for UIWebView.

**Comment by FedoB** [comment]
Can confirm that typing
`gestures.disable_swipe_to_close(nav)`
after presenting the view, does resolve the error.
I was getting the error when that line of code was before `present`
